const usersData = [
  {id: 0, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Convidado', status: 'Pending'},
  {id: 1, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 2, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Active'},
  {id: 3, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 4, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Active'},
  {id: 5, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 6, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Administrador', status: 'Banned'},
  {id: 7, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 8, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 9, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Administrador', status: 'Active'},
  {id: 10, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Banned'},
  {id: 11, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 12, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Pending'},
  {id: 13, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 14, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 15, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Banned'},
  {id: 16, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 17, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Active'},
  {id: 18, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Pending'},
  {id: 19, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 20, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 21, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 22, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 23, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 24, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Inativo'},
  {id: 25, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Membro', status: 'Active'},
  {id: 42, name: 'Marcos Fernandes', registered: '2019/01/01', role: 'Funcionário', status: 'Não entre em pânico!'},
  
]

export default usersData
